#!/usr/bin/env bash
# Generate the gitignored local .env files with dev defaults when missing.
# Optional Cursor secrets (e.g. TMDB_API_KEY) are injected when present in the
# environment so enriched features light up without editing files by hand.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DATABASE_URL_LOCAL="postgres://postgres:postgres@localhost:5432/still"
SERVER_ENV="$REPO_ROOT/apps/server/.env"
WEB_ENV="$REPO_ROOT/apps/web/.env"

if [ ! -f "$SERVER_ENV" ]; then
  echo "[env] Writing apps/server/.env"
  SECRET="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 48)"
  {
    echo "# Local dev environment (generated by .cursor/write-env.sh)"
    echo "DATABASE_URL=$DATABASE_URL_LOCAL"
    echo "BETTER_AUTH_SECRET=$SECRET"
    echo "BETTER_AUTH_URL=http://localhost:3001"
    echo "CORS_ORIGIN=http://localhost:3001"
    echo "NODE_ENV=development"
  } > "$SERVER_ENV"
else
  echo "[env] apps/server/.env exists — leaving as-is"
fi

if [ ! -f "$WEB_ENV" ]; then
  echo "[env] Writing apps/web/.env"
  {
    echo "# Local dev environment (generated by .cursor/write-env.sh)"
    echo "NEXT_PUBLIC_SERVER_URL=http://localhost:3001"
    echo "API_REWRITE_ORIGIN=http://localhost:3000"
  } > "$WEB_ENV"
else
  echo "[env] apps/web/.env exists — leaving as-is"
fi

# Inject optional secrets from the environment (Cursor secrets) if provided and
# not already present in the server .env.
inject_secret() {
  local key="$1"
  local val="${!key:-}"
  if [ -n "$val" ] && ! grep -q "^${key}=" "$SERVER_ENV"; then
    echo "[env] Injecting $key from environment into apps/server/.env"
    echo "${key}=${val}" >> "$SERVER_ENV"
  fi
}
for k in TMDB_API_KEY TMDB_WATCH_REGION STREAMING_AVAILABILITY_API_KEY \
         GOOGLE_GENERATIVE_AI_API_KEY AI_GATEWAY_API_KEY \
         UPSTASH_REDIS_REST_URL UPSTASH_REDIS_REST_TOKEN; do
  inject_secret "$k"
done
