/** Server product funnel kinds — keep in sync with `apps/server/src/lib/product-event-kinds.ts`. */
export const PRODUCT_EVENT_KINDS = [
	"import.letterboxd.completed",
	"import.anilist.completed",
	"log.first_created",
	"onboarding.completed",
	"taste_card.shared",
	"taste.dismissed",
	"taste.for_you.served",
	"showcase.edited",
	"post_log.celebrate",
	"viral_review.tapped",
	"journal.read",
	"wrapped.viewed",
	"wrapped.shared",
	"members.followed",
	"streaming_alert.sent",
	"person_favorite.add",
	"person_favorite.remove",
	"person_favorite_alert.sent",
	"quote.upvote",
	"quote.save",
	"quote.unsave",
	"quote.submit",
	"realtime.presence.join",
	"realtime.presence.leave",
	"realtime.list.coedit",
	"realtime.comment.received_live",
	"realtime.notification.push_received",
	"realtime.list.sync_conflict",
	"today.viewed",
	"today.pick.viewed",
	"today.pick.action",
	"today.week.viewed",
	"today.week.action",
	"today.circle.viewed",
	"today.circle.action",
	"rating.category_saved",
	"rating.category_skipped",
	"rating.suggestion_applied",
	"recommendation.sent",
	"recommendation.opened",
	"recommendation.accepted",
	"recommendation.answered",
] as const;

export type ProductEventKind = (typeof PRODUCT_EVENT_KINDS)[number];

/** Kinds the web app may POST via `/api/product-events`. */
export const CLIENT_PRODUCT_EVENT_KINDS = [
	"onboarding.completed",
	"taste_card.shared",
	"post_log.celebrate",
	"viral_review.tapped",
	"journal.read",
	"wrapped.viewed",
	"wrapped.shared",
	"members.followed",
	"realtime.presence.join",
	"realtime.presence.leave",
	"realtime.comment.received_live",
	"realtime.notification.push_received",
	"today.viewed",
	"today.pick.viewed",
	"today.pick.action",
	"today.week.viewed",
	"today.week.action",
	"today.circle.viewed",
	"today.circle.action",
	"rating.category_saved",
	"rating.category_skipped",
	"rating.suggestion_applied",
] as const;

export type ClientProductEventKind =
	(typeof CLIENT_PRODUCT_EVENT_KINDS)[number];
